apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-server
  labels:
    app: helloworld-server
spec:
  selector:
    matchLabels:
      app: helloworld-server
  template:
    metadata:
      labels:
        app: helloworld-server
    spec:
      containers:
        - name: helloworld-server
          image: helloworld-server
          ports:
            - containerPort: 50051
          resources:
            requests:
              cpu: "10m"
---
apiVersion: v1
kind: Service
metadata:
  name: helloworld-server
  labels:
    app: helloworld-server
spec:
  ports:
    - port: 80
      targetPort: 50051
      protocol: TCP
  selector:
    app: helloworld-server
